In [16]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import torch

pe = torch.arange(0,5)
print(pe.shape)
pe = torch.arange(0,5).unsqueeze(1)
print(pe.shape)
pe

torch.Size([5])
torch.Size([5, 1])


tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [4]:
x = torch.tensor([10, 20, 30])
print(x.shape) 
x

torch.Size([3])


tensor([10, 20, 30])

In [7]:
y = x.unsqueeze(0)
print(y.shape) 
y

torch.Size([1, 3])


tensor([[10, 20, 30]])

In [8]:
y = x.unsqueeze(1)
print(y.shape) 
y

torch.Size([3, 1])


tensor([[10],
        [20],
        [30]])

In [9]:
x = torch.tensor([[5],
                  [6],
                  [7]])

In [11]:
print(x.shape)   # torch.Size([3, 1])

y = x.squeeze(1)
print(y.shape)  
y

torch.Size([3, 1])
torch.Size([3])


tensor([5, 6, 7])

In [ ]:
div = torch.exp(torch.arange(0,6,2,dtype=torch.float32)
print(div.shape)
div

torch.Size([3])


tensor([0., 2., 4.])

In [15]:
pe

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [18]:
pe*div

tensor([[ 0.,  0.,  0.],
        [ 0.,  2.,  4.],
        [ 0.,  4.,  8.],
        [ 0.,  6., 12.],
        [ 0.,  8., 16.]])

In [93]:
pe = torch.zeros(10,6)
# pe=pe.unsqueeze(1)
pe

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [100]:
position = torch.arange(0,10,dtype=torch.float32)
position.shape

torch.Size([10])

In [89]:
import math
positions = torch.arange(0,10).unsqueeze(0)
positions

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
div_term = torch.exp(torch.arange(0,6,2)*(-math.log(10000.0))/6)
div_term

tensor([1.0000, 0.0464, 0.0022])

In [46]:
positions*div_term

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 4.6416e-02, 2.1544e-03],
        [2.0000e+00, 9.2832e-02, 4.3089e-03],
        [3.0000e+00, 1.3925e-01, 6.4633e-03],
        [4.0000e+00, 1.8566e-01, 8.6177e-03],
        [5.0000e+00, 2.3208e-01, 1.0772e-02],
        [6.0000e+00, 2.7850e-01, 1.2927e-02],
        [7.0000e+00, 3.2491e-01, 1.5081e-02],
        [8.0000e+00, 3.7133e-01, 1.7235e-02],
        [9.0000e+00, 4.1774e-01, 1.9390e-02]])

In [ ]:
pe[:,0::2] = torch.sin(positions*div_term)
pe[:,1::2] = torch.cos(positions)

In [39]:
pe

tensor([[0.8415, 0.5403, 0.0464, 0.9989, 0.0022, 1.0000],
        [0.8415, 0.5403, 0.0464, 0.9989, 0.0022, 1.0000],
        [0.8415, 0.5403, 0.0464, 0.9989, 0.0022, 1.0000],
        [0.8415, 0.5403, 0.0464, 0.9989, 0.0022, 1.0000],
        [0.8415, 0.5403, 0.0464, 0.9989, 0.0022, 1.0000],
        [0.8415, 0.5403, 0.0464, 0.9989, 0.0022, 1.0000],
        [0.8415, 0.5403, 0.0464, 0.9989, 0.0022, 1.0000],
        [0.8415, 0.5403, 0.0464, 0.9989, 0.0022, 1.0000],
        [0.8415, 0.5403, 0.0464, 0.9989, 0.0022, 1.0000],
        [0.8415, 0.5403, 0.0464, 0.9989, 0.0022, 1.0000]])

In [87]:
d_model = 20
seq_len = 8
pe = torch.zeros(seq_len,d_model).unsqueeze(2)
pe.shape

torch.Size([8, 20, 1])

In [83]:
print(pe.shape)
print(pe[0].shape)
pe

torch.Size([1, 8, 20])
torch.Size([8, 20])


tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [86]:

print(pe.shape)
print(pe[0].shape)
pe

torch.Size([8, 1, 20])
torch.Size([1, 20])


tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [88]:
print(pe.shape)
print(pe[0].shape)
pe

torch.Size([8, 20, 1])
torch.Size([20, 1])


tensor([[[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
    

In [119]:
x = torch.arange(0,30,dtype=torch.float32)
x = x.reshape(2,5,3)
x

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.],
         [12., 13., 14.]],

        [[15., 16., 17.],
         [18., 19., 20.],
         [21., 22., 23.],
         [24., 25., 26.],
         [27., 28., 29.]]])

In [ ]:
x.mean(dim=-1,keepdim=True)

tensor([[[ 1.],
         [ 4.],
         [ 7.],
         [10.],
         [13.]],

        [[16.],
         [19.],
         [22.],
         [25.],
         [28.]]])

In [ ]:
x.mean(dim=-1,keepdim=True)

In [21]:
matrix = torch.arange(0,512*768)
matrix = matrix.reshape(512,768)
print(matrix.shape)
matrix = matrix.unsqueeze(0)
print(matrix.shape)
matrix

torch.Size([512, 768])
torch.Size([1, 512, 768])


tensor([[[     0,      1,      2,  ...,    765,    766,    767],
         [   768,    769,    770,  ...,   1533,   1534,   1535],
         [  1536,   1537,   1538,  ...,   2301,   2302,   2303],
         ...,
         [390912, 390913, 390914,  ..., 391677, 391678, 391679],
         [391680, 391681, 391682,  ..., 392445, 392446, 392447],
         [392448, 392449, 392450,  ..., 393213, 393214, 393215]]])

In [27]:
matrix.reshape(1,512,12,64)
matrix.reshape(1,512,12,64).transpose(1,2)

tensor([[[[     0,      1,      2,  ...,     61,     62,     63],
          [    64,     65,     66,  ...,    125,    126,    127],
          [   128,    129,    130,  ...,    189,    190,    191],
          ...,
          [   576,    577,    578,  ...,    637,    638,    639],
          [   640,    641,    642,  ...,    701,    702,    703],
          [   704,    705,    706,  ...,    765,    766,    767]],

         [[   768,    769,    770,  ...,    829,    830,    831],
          [   832,    833,    834,  ...,    893,    894,    895],
          [   896,    897,    898,  ...,    957,    958,    959],
          ...,
          [  1344,   1345,   1346,  ...,   1405,   1406,   1407],
          [  1408,   1409,   1410,  ...,   1469,   1470,   1471],
          [  1472,   1473,   1474,  ...,   1533,   1534,   1535]],

         [[  1536,   1537,   1538,  ...,   1597,   1598,   1599],
          [  1600,   1601,   1602,  ...,   1661,   1662,   1663],
          [  1664,   1665,   1666,  ...,  

tensor([[[[     0,      1,      2,  ...,     61,     62,     63],
          [   768,    769,    770,  ...,    829,    830,    831],
          [  1536,   1537,   1538,  ...,   1597,   1598,   1599],
          ...,
          [390912, 390913, 390914,  ..., 390973, 390974, 390975],
          [391680, 391681, 391682,  ..., 391741, 391742, 391743],
          [392448, 392449, 392450,  ..., 392509, 392510, 392511]],

         [[    64,     65,     66,  ...,    125,    126,    127],
          [   832,    833,    834,  ...,    893,    894,    895],
          [  1600,   1601,   1602,  ...,   1661,   1662,   1663],
          ...,
          [390976, 390977, 390978,  ..., 391037, 391038, 391039],
          [391744, 391745, 391746,  ..., 391805, 391806, 391807],
          [392512, 392513, 392514,  ..., 392573, 392574, 392575]],

         [[   128,    129,    130,  ...,    189,    190,    191],
          [   896,    897,    898,  ...,    957,    958,    959],
          [  1664,   1665,   1666,  ...,  

In [18]:
test = matrix @ torch.rand(768,768)
matrix.shape
matrix.reshape(1,512,12,64)

torch.Size([1, 512, 768])

tensor([[[[0.0000e+00, 1.0000e+00, 2.0000e+00,  ..., 6.1000e+01,
           6.2000e+01, 6.3000e+01],
          [6.4000e+01, 6.5000e+01, 6.6000e+01,  ..., 1.2500e+02,
           1.2600e+02, 1.2700e+02],
          [1.2800e+02, 1.2900e+02, 1.3000e+02,  ..., 1.8900e+02,
           1.9000e+02, 1.9100e+02],
          ...,
          [5.7600e+02, 5.7700e+02, 5.7800e+02,  ..., 6.3700e+02,
           6.3800e+02, 6.3900e+02],
          [6.4000e+02, 6.4100e+02, 6.4200e+02,  ..., 7.0100e+02,
           7.0200e+02, 7.0300e+02],
          [7.0400e+02, 7.0500e+02, 7.0600e+02,  ..., 7.6500e+02,
           7.6600e+02, 7.6700e+02]],

         [[7.6800e+02, 7.6900e+02, 7.7000e+02,  ..., 8.2900e+02,
           8.3000e+02, 8.3100e+02],
          [8.3200e+02, 8.3300e+02, 8.3400e+02,  ..., 8.9300e+02,
           8.9400e+02, 8.9500e+02],
          [8.9600e+02, 8.9700e+02, 8.9800e+02,  ..., 9.5700e+02,
           9.5800e+02, 9.5900e+02],
          ...,
          [1.3440e+03, 1.3450e+03, 1.3460e+03,  ..., 1.4050

In [14]:
print(test.shape)

torch.Size([1, 512, 768])


In [28]:
-1e9

-1000000000.0

In [3]:
import torch
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
torch.cat([tensor1,tensor2])

tensor([1, 2, 3, 1, 2, 3])

In [4]:
import torch
tensor1 = torch.tensor(1).unsqueeze(0)
tensor2 = torch.tensor(3).unsqueeze(0)
torch.cat([tensor1,tensor2])

tensor([1, 3])